### ISSUE TITLE
allow for cross-project portable model referencing

### ISSUE THREAD

**Issue by abstratt** [abstratt/textuml#109]
The load directive allows a model to reference (import a model, apply a profile) that are not in the current project. But it requires a URI, and URIs are usually fixed, which makes those references non-portable. We need a way to make project cross-references that are portable.

**Comment by abstratt** [comment]
Some ideas:
- mdd.properties could allow one to declare a list of comma-separated URIs that should be added to the project's build path (similar to the load directive, but external to the .tuml file).
- mdd.properties would allow one to define placeholders that could then be used in load directives in the .tuml file. This requires a change to the language to allow placeholders to be referenced in the load directive.

**Comment by ajesh77** [comment]
Would like the 1st approach as it would be easy for the developer to just configure the referenced models in the property file and ensure that they are available in the class path. With this, how would the href on imported package look like ?

**Comment by ajesh77** [comment]
One other alternative would be to have a system configuration (environment) for the maven/UML artifact repository. TextUML can use this configuration and create URI for each of the UML files found in the repor path. We can introduce a new schema to map these files and this would reduce the property configuration if the project had multiple models running into multiple modules.

**Comment by abstratt** [comment]
@ajesh77 I think this would accomplish what you need:

* we allow location variables to be declared in the mdd.properties file
* we allow said variables to appear in load primitives

For example:

mdd.properties:

``` 
mdd.location.vars.foo=http://...
mdd.location.vars.bar=file://...
mdd.location.vars.fred=1.4.0
```

sample.tuml:

```
package mypackage;

load <<${foo}/othermodel.uml>>;
load <<${bar}/.../${fred}/...>>;
...
```
Then your Maven-based build process could configure those properties in mdd.properties according to the current environment before compiling the model.

**Comment by abstratt** [comment]
Actual solution involves:

- replacing use of load with absolute URI with a property in mdd.properties that can include absoolute URIs
- user model still needs to import the external model (by name) to access it

@ajesh77 Please see commit ff303cd which includes a test case that shows this.
