### ISSUE TITLE
Visibility for primitives

### ISSUE THREAD

**Issue by simonjwright** [abstratt/textuml#120]
There seems to be no way of specifying modifiers for primitives. Is this by design?
I think the only modifier that would be needed would be the visibility.

**Comment by abstratt** [comment]
There isn't support for visibility on primitives, @simonjwright. Should be easy to add.

For enumerations, the expectation is that there is support. What do you see? A compilation error? Or the visibility just doesn't stick?

**Comment by simonjwright** [comment]
I should explain that I’m thinking of replacing ArgoUML in my [ColdFrame](https://sourceforge.net/projects/coldframe/), which generates framework Ada, by something using the syntax of TextUML but implemented in Python & [PLY](http://www.dabeaz.com/ply/). I’ve been working from `textuml.scc` - PLY is less forgiving about conflicts than SableCC, it seems! - and came across primitives and enumerations vs visibility. I hope it’s OK to report issues which seem independent of the implementation.
I took enumerations off the title of this issue because, on looking again, I see that `textuml.scc` regards them as a type of class. But, on third thoughts, I wonder why? (especially because the docs still correspond to the commented-out `enumeration_def` at `textuml.scc:621`). If the point was to allow slot definitions - not familiar with that term, but reading between the lines - could we have used syntax like
```
enumeration foo
    bar = 1,
    quux = 42
end;
```

**Comment by abstratt** [comment]
Added support for visibility on primitives.

**Comment by abstratt** [comment]
@simonjwright Fixed the doc to reflect the change in the basic enumeration syntax.

The changes in enumeration syntax were to support assigning values to attributes for each literal (see #40):

```
enumeration Foo 
    attribute attr1 : Integer;
    attribute attr2 : String;    
    literal id1(attr1 := 5, attr2 := "foo");     
    literal id2(attr1 := 17, attr2 := "bar");     
end;

```

**Comment by simonjwright** [comment]
I see, thanks. Not a capability I need to support. Now I just have to work out why I’m getting reduce/reduce conflicts ...

**Comment by abstratt** [comment]
@simonjwright BTW - slots refer to values for properties in an instance of a classifier. Enumeration literals are instance specifications typed by the enumeration.

**Comment by simonjwright** [comment]
On 6 Apr 2017, at 14:48, Rafael Chaves <notifications@github.com> wrote:

> @simonjwright <https://github.com/simonjwright> BTW - slots refer to values for properties in an instance of a classifier. Enumeration literals are instance specifications typed by the enumeration.

I see that, I think. Your example was clear. I've just never thought of doing that; used to 3GL enumerations (e.g. Ada `type Colour is (Red, Green, Blue);` which would often be used in several classes in the package, so tying them to a particular class would be inconvenient.

**Comment by abstratt** [comment]
@simonjwright Actually, the classifier I referring to was the enumeration itself. The enumeration itself is not tied to any other class, and be used everywhere - the enumeration values are instances typed by the enumeration. Slots specify values for properties for an instance of any classifier, including enumerations.
