### ISSUE TITLE
Error installing from Marketplace

### ISSUE THREAD

**Issue by MaSven** [abstratt/textuml#147]
> An error occurred while collecting items to be installed
session context was:(profile=_home_sven_eclipse_modeling-oxygen2_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at jar:http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/mdd/com.abstratt.mdd.oss.repository/2.2/com.abstratt.mdd.oss.repository-2.2.zip!/plugins/com.abstratt.mdd.modelrenderer.uml2dot_2.2.201709.201803152142.jar.
Read timed out

The problem seems to be the url.

**Comment by abstratt** [comment]
@MaSven  This is really just a timeout - the repository at Cloudbees is quite slow, and times out frequently.

A new attempt should eventually get past the problem.

The URL is valid inside the Java VM, but it won't work elsewhere. It is a JAR URL (jar:\<baseURL\>!/\<internal-path\>). The base URL in this case is http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/mdd/com.abstratt.mdd.oss.repository/2.2/com.abstratt.mdd.oss.repository-2.2.zip, which you can see is valid.

**Comment by MaSven** [comment]
ok thank you.

**Comment by abstratt** [comment]
An alternative if you can't get it work without hitting a timeout is to download the repository as a ZIP file (URL above), and then install from the local repository.

![image](https://user-images.githubusercontent.com/2187522/37868865-95ba5e06-2f8c-11e8-9996-11ec35e50430.png)

**Comment by abstratt** [comment]
@MaSven (but then I think you will lose automatic updates)

**Comment by MaSven** [comment]
Thank you but it was installed successfully. Don't know why this error was there when it was installed correctly.
