### ISSUE TITLE
"object (from mdd_types)" box

### ISSUE THREAD

**Issue by lmaag182** [abstratt/textuml#79]
The box appears in "&showElementsInOtherPackage=Immediate"  mode in the cloudfier enviroment. This is not necessary and confuses the rest of the model (See attachment). 
![mdd_types](https://cloud.githubusercontent.com/assets/11016986/8520550/84e963c0-23db-11e5-9fd1-60191df432a9.png)

**Comment by abstratt** [comment]
I am implementing the ability of not showing elements from libraries (which will be the default).

Note that this change only affects how models are rendered (i.e. the diagramsd. In the actual models, classes will continue to inherit from mdd_types::Object as that is currently required for Cloudfier applications. If running a model as a Cloudfier application and/or executable models are not required, you can disable that by having this in your mdd.properties file:

```
mdd.extendBaseObject=false
```  
or remove the entry entirely.

**Comment by abstratt** [comment]
This feature is going to be deployed shortly. @lmaag182  if you want to bring library elements such as mdd_types::Object back to the diagrams, you will need to specify 'showLibraries=true'.

**Comment by abstratt** [comment]
Deployed and available.

Examples:

### Hiding library elements (default)
![](http://develop.cloudfier.com/services/diagram/test-cloudfier-examples-car-rental/package/car_rental.uml?showClasses=true&showLibraries=false&showElementsInOtherPackage=Immediate)

### Showing library elements
![](http://develop.cloudfier.com/services/diagram/test-cloudfier-examples-car-rental/package/car_rental.uml?showClasses=true&showLibraries=true&showElementsInOtherPackage=Immediate)

**Comment by lmaag182** [comment]
Sweet! Thank you.
