### ISSUE TITLE
Can't install on Mars

### ISSUE THREAD

**Issue by martinppp** [abstratt/textuml#84]
I try to install from Marketplace and from install new software method. Both give me this exception:

Unable to read repository at jar:http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/mdd/com.abstratt.mdd.oss.repository/2.1/com.abstratt.mdd.oss.repository-2.1.zip!/content.xml.
Unable to read repository at jar:http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/mdd/com.abstratt.mdd.oss.repository/2.1/com.abstratt.mdd.oss.repository-2.1.zip!/content.xml.
Read timed out

Eclipse Modeling Tools

Version: Mars Release (4.5.0)
Build id: 20150621-1200

Java SDK: jdk1.8.0_25.jdk
OS: Mac OSX Yosemite version: 10.10.4 (14E46)

**Comment by abstratt** [comment]
Installing from a zipped update site is pretty slow in Eclipse, and I guess it is prone to latency issues. I have seen timeouts in the past, and they tend to be temporary.

A workaround may be to download the update site:

http://repository-textuml.forge.cloudbees.com/snapshot/com/abstratt/mdd/com.abstratt.mdd.oss.repository/2.1/com.abstratt.mdd.oss.repository-2.1.zip

and then add that ZIP file as an archived repository in Eclipse (Help > Install new software > Add... > Archive... 

I am not sure whether that allows you to continue to receive updates though.

**Comment by martinppp** [comment]
I Install it from the archive. It is working now.

Thanks for your fast answer,

Martin
