### ISSUE TITLE
support for Japanese characters in names of model elements

### ISSUE THREAD

**Issue by abstratt** [abstratt/textuml#86]
Should support Japanese characters (really, from any language, Japanese is just an example that sets the bar really high) in user defined model symbols, such as names of packages, classes, attributes etc.

**Comment by abstratt** [comment]
In the TextUML Toolkit it is possible to use Portuguese characters like in this:

```
package test;

import mdd_types;

class Corpo\ Humano
    attribute cora\ç\ão : Cora\ç\ão;
end;

class Cora\ç\ão
end;

end.
```

That does not work in Cloudfier though, only in the Eclipse plug-in. Also, even if escaping helped, for Japanese, every character would have to be escaped, which would be really painful.

**Comment by abstratt** [comment]
CC: @atanaka Took me a while but this is finally addressed!

**Comment by atanaka** [comment]
Thank you very much!  I tested with plugin, and was able to create attached diagram.  Great work!  I will check with cloudfier next.

![i18n](https://user-images.githubusercontent.com/872393/29558202-673b0afe-8766-11e7-8779-8cf3f152914e.png)

**Comment by abstratt** [comment]
@atanaka Thank you for verifying it!

**Comment by atanaka** [comment]
Hello again,

I am using Mac so I tried with Safari first with very simple model, but it showed kind of strange behavior, i.e. when I typed in Japanese characters and hit enter key they just disappeared to nothing with error mark, or in some cases after several seconds they were accepted correctly.  I tried several times but got the same result.  The error mark I think is probably related to client-server communication.  I then switched my browser to FireFox, and it worked fine, i.e. Japanese characters were accepted without strange behavior and I was able to generate web app.
<img width="807" alt="test" src="https://user-images.githubusercontent.com/872393/29599358-1c3d3ad2-880a-11e7-9bf4-07482727cf72.png">
I then tried Chrome browser.  It worked the same way as FireFox.  As a conclusion, except for strange behavior of Safari browser, it seems to work with Cloudier on Mac.  :)

**Comment by abstratt** [comment]
Thanks, @atanaka! That is good info. Would you be able to try the same over https://orionhub.org (by editing plain text files)? Just trying to figure out whether this is a bug in Orion itself (I don't have access to a Mac or Safari).

**Comment by abstratt** [comment]
@atanaka Actually, a Java or Javascript file will be better, as they have syntax highlighting, which could be another venue for issues.

Also, it is possible the behavior you saw could have happened with non-Japanese chars as well. Did you try making edits/changes to areas using only ASCII characters?

**Comment by atanaka** [comment]
Regarding this test, there was no strange behavior like the one I
encountered with Cloudfier in editing Japanese text (I created memo.tuml
text file and edited with some Japanese characters).

Regards,
Akira

**Comment by atanaka** [comment]
I tried the following.

On Wed, Aug 23, 2017 at 9:13 PM, Rafael Chaves <notifications@github.com>
wrote:

> @atanaka <https://github.com/atanaka> Actually, a Java or Javascript file
> will be better, as they have syntax highlighting, which could be another
> venue for issues.
>

With Java and JavaScript, I encountered the same strange behavior with
Safari. I also tried this with FireFox, there was no problem.

Also, it is possible the behavior you saw could have happened with
> non-Japanese chars as well. Did you try making edits/changes to areas using
> only ASCII characters?
>

Actually that's what I did.  I copied sample code from somewhere containing
e.g. "Hello World!" (for Java and for JavaScript) and tried to modify e.g.
"Hello World!" with Japanese characters.

Regards,
Akira

**Comment by abstratt** [comment]
@atanaka Thanks - that means it is indeed an Orion bug. I will report it upstream. Cheers!

**Comment by abstratt** [comment]
@atanaka This is the upstream bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=521338

**Comment by atanaka** [comment]
Thank you for the bug report.  I hope they can react to it soon.
